### PR TITLE
reflect api change in tinyxml and urdfdom in melodic

### PR DESCRIPTION
**Pull request by LinYuChi**
I do not have kinetic in hand, please check if this works with kinetic, too. If not, please reject this pull request, and use this branch when using melodic.

### CODE REVIEW

**Comment by dmcconachie** [comment]
Does not compile on 16.04 and ROS Kinetic:

```
catkin_ws/src/openrave_tools/or_urdf/src/catkin_finder.cpp: In function ‘std::__cxx11::string {anonymous}::getPackageNameFromXML(const string&)’:
catkin_ws/src/openrave_tools/or_urdf/src/catkin_finder.cpp:30:74: error: ‘class tinyxml2::XMLDocument’ has no member named ‘ErrorStr’; did you mean ‘Error’?
     RAVELOG_WARN("Failed loading package.xml file '%s': %s\n",
                                                                          ^       
                                                                          Error
openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/build.make:86: recipe for target 'openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/src/catkin_finder.cpp.o' failed
make[2]: *** [openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/src/catkin_finder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
catkin_ws/src/openrave_tools/or_urdf/src/urdf_loader.cpp: In member function ‘void or_urdf::URDFLoader::ParseURDF(urdf::Model&, std::vector<boost::shared_ptr<OpenRAVE::KinBody::LinkInfo> >&, std::vector<boost::shared_ptr<OpenRAVE::KinBody::JointInfo> >&)’:
catkin_ws/src/openrave_tools/or_urdf/src/urdf_loader.cpp:260:39: error: conversion from ‘const boost::shared_ptr<urdf::Collision>’ to non-scalar type ‘const std::shared_ptr<urdf::Collision>’ requested
         BOOST_FOREACH (const std::shared_ptr<urdf::Collision> collision,
openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/build.make:62: recipe for target 'openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/src/urdf_loader.cpp.o' failed
make[2]: *** [openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/src/urdf_loader.cpp.o] Error 1
CMakeFiles/Makefile2:19247: recipe for target 'openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/all' failed
make[1]: *** [openrave_tools/or_urdf/CMakeFiles/or_urdf_plugin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by LinYuChi** [comment]
Sigh... as I expected. I will close this pull request.
